name: calipso-tool-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - hdf5
  - pyhdf
  - numpy
  - pandas
  - pdal
  - python-pdal
  - pip
  - uv
  - ipykernel
  - pip:
    - laspy
    - click

